-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color18 = '#373943'
local Color14 = '#cbccd2'
local Color9 = '#ff6188'
local Color11 = '#858790'
local Color13 = '#12141a'
local Color6 = '#78e8c6'
local Color4 = '#ffd866'
local Color8 = '#ab9df2'
local Color0 = '#b7d175'
local Color12 = '#171921'
local Color7 = '#a9dc76'
local Color1 = '#555763'
local Color10 = '#fc9867'
local Color15 = '#242d25'
local Color16 = '#332025'
local Color17 = '#2b2e37'
local Color3 = '#78dce8'
local Color5 = '#57595f'
local Color2 = '#fc6a67'
local Color19 = '#98a2b5'

highlight('Type', nil, Color0, nil)
highlight('Comment', nil, Color1, 'italic')
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('String', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Identifier', nil, Color9, nil)
highlight('Number', nil, Color10, nil)
highlight('StatusLine', Color11, Color12, nil)
highlight('WildMenu', Color13, Color14, nil)
highlight('Pmenu', Color13, Color14, nil)
highlight('PmenuSel', Color14, Color13, nil)
highlight('PmenuThumb', Color13, Color14, nil)
highlight('DiffAdd', Color15, nil, nil)
highlight('DiffDelete', Color16, nil, nil)
highlight('Normal', Color13, Color14, nil)
highlight('Visual', Color17, nil, nil)
highlight('CursorLine', Color17, nil, nil)
highlight('ColorColumn', Color17, nil, nil)
highlight('SignColumn', Color13, nil, nil)
highlight('LineNr', nil, Color18, nil)
highlight('TabLine', Color12, Color1, nil)
highlight('TabLineSel', Color19, Color13, nil)
highlight('TabLineFill', Color12, Color1, nil)
highlight('TSPunctDelimiter', nil, Color14, nil)

link('TSParameterReference', 'TSParameter')
link('TSOperator', 'Operator')
link('TSString', 'String')
link('TSKeyword', 'Keyword')
link('Operator', 'Keyword')
link('Whitespace', 'Comment')
link('TSNumber', 'Number')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSParameter', 'Constant')
link('TSField', 'Constant')
link('TSPunctBracket', 'MyTag')
link('Conditional', 'Operator')
link('TSFunction', 'Function')
link('CursorLineNr', 'Identifier')
link('TSRepeat', 'Repeat')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Macro', 'Function')
link('TSFuncMacro', 'Macro')
link('TSTagDelimiter', 'Type')
link('Folded', 'Comment')
link('TelescopeNormal', 'Normal')
link('NonText', 'Comment')
link('TSTag', 'MyTag')
link('TSNamespace', 'TSType')
link('TSFloat', 'Number')
link('TSConditional', 'Conditional')
link('TSConstant', 'Constant')
link('TSComment', 'Comment')
link('Repeat', 'Conditional')
link('TSLabel', 'Type')
link('TSProperty', 'TSField')
link('TSType', 'Type')
