-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color15 = '#202e25'
local Color18 = '#3b2b2b'
local Color7 = '#639E29'
local Color11 = '#1c1616'
local Color16 = '#391f1f'
local Color5 = '#614e4e'
local Color1 = '#503939'
local Color12 = '#917878'
local Color13 = '#caa5a5'
local Color14 = '#221b1b'
local Color2 = '#C13838'
local Color8 = '#BAB13B'
local Color19 = '#d35386'
local Color0 = '#7E9E2D'
local Color6 = '#4EAAA4'
local Color9 = '#D65151'
local Color4 = '#C48519'
local Color3 = '#BA9D6F'
local Color10 = '#D1711D'
local Color17 = '#43252f'

highlight('Type', nil, Color0, nil)
highlight('Comment', nil, Color1, 'italic')
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('String', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Identifier', nil, Color9, nil)
highlight('Number', nil, Color10, nil)
highlight('StatusLine', Color12, Color11, nil)
highlight('WildMenu', Color14, Color13, nil)
highlight('Pmenu', Color14, Color13, nil)
highlight('PmenuSel', Color13, Color14, nil)
highlight('PmenuThumb', Color14, Color13, nil)
highlight('DiffAdd', Color15, nil, nil)
highlight('DiffDelete', Color16, nil, nil)
highlight('Normal', Color14, Color13, nil)
highlight('Visual', Color17, nil, nil)
highlight('CursorLine', Color17, nil, nil)
highlight('ColorColumn', Color17, nil, nil)
highlight('SignColumn', Color14, nil, nil)
highlight('LineNr', nil, Color18, nil)
highlight('TabLine', Color11, Color1, nil)
highlight('TabLineSel', Color19, Color14, nil)
highlight('TabLineFill', Color11, Color1, nil)
highlight('TSPunctDelimiter', nil, Color13, nil)

link('Folded', 'Comment')
link('Operator', 'Keyword')
link('Macro', 'Function')
link('TSParameter', 'Constant')
link('CursorLineNr', 'Identifier')
link('TSNamespace', 'TSType')
link('TSConditional', 'Conditional')
link('TSLabel', 'Type')
link('TSKeyword', 'Keyword')
link('TSFuncMacro', 'Macro')
link('TSString', 'String')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSOperator', 'Operator')
link('Conditional', 'Operator')
link('Repeat', 'Conditional')
link('TSParameterReference', 'TSParameter')
link('TSNumber', 'Number')
link('TSConstant', 'Constant')
link('TSRepeat', 'Repeat')
link('TSField', 'Constant')
link('TSFloat', 'Number')
link('TSTagDelimiter', 'Type')
link('TelescopeNormal', 'Normal')
link('TSTag', 'MyTag')
link('TSPunctBracket', 'MyTag')
link('TSFunction', 'Function')
link('TSProperty', 'TSField')
link('TSType', 'Type')
link('NonText', 'Comment')
link('Whitespace', 'Comment')
link('TSComment', 'Comment')
link('TSPunctSpecial', 'TSPunctDelimiter')
