-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color11 = '#16252d'
local Color5 = '#5e6d75'
local Color3 = '#5fb2df'
local Color16 = '#38323d'
local Color4 = '#f6cc73'
local Color18 = '#37505e'
local Color13 = '#1a2b34'
local Color14 = '#d1dce2'
local Color6 = '#59c6c8'
local Color10 = '#DC8255'
local Color8 = '#978dd6'
local Color0 = '#A4EF58'
local Color7 = '#97c892'
local Color15 = '#293e3f'
local Color12 = '#889ba5'
local Color2 = '#B4552D'
local Color9 = '#ee5d75'
local Color1 = '#4f6e7f'
local Color17 = '#314845'

highlight('Type', nil, Color0, nil)
highlight('Comment', nil, Color1, 'italic')
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('String', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Identifier', nil, Color9, nil)
highlight('Number', nil, Color10, nil)
highlight('StatusLine', Color12, Color11, nil)
highlight('WildMenu', Color13, Color14, nil)
highlight('Pmenu', Color13, Color14, nil)
highlight('PmenuSel', Color14, Color13, nil)
highlight('PmenuThumb', Color13, Color14, nil)
highlight('DiffAdd', Color15, nil, nil)
highlight('DiffDelete', Color16, nil, nil)
highlight('Normal', Color13, Color14, nil)
highlight('Visual', Color17, nil, nil)
highlight('CursorLine', Color17, nil, nil)
highlight('ColorColumn', Color17, nil, nil)
highlight('SignColumn', Color13, nil, nil)
highlight('LineNr', nil, Color18, nil)
highlight('TabLine', Color11, Color1, nil)
highlight('TabLineSel', Color7, Color13, nil)
highlight('TabLineFill', Color11, Color1, nil)
highlight('TSPunctDelimiter', nil, Color14, nil)

link('TSConstant', 'Constant')
link('TSType', 'Type')
link('Repeat', 'Conditional')
link('TSNamespace', 'TSType')
link('TSConditional', 'Conditional')
link('TSString', 'String')
link('TSTagDelimiter', 'Type')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Operator', 'Keyword')
link('TSTag', 'MyTag')
link('TSFloat', 'Number')
link('TSComment', 'Comment')
link('Whitespace', 'Comment')
link('TSProperty', 'TSField')
link('CursorLineNr', 'Identifier')
link('TSNumber', 'Number')
link('TSRepeat', 'Repeat')
link('TSFuncMacro', 'Macro')
link('TSParameter', 'Constant')
link('TSOperator', 'Operator')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSParameterReference', 'TSParameter')
link('Conditional', 'Operator')
link('NonText', 'Comment')
link('TSLabel', 'Type')
link('Macro', 'Function')
link('TSField', 'Constant')
link('TelescopeNormal', 'Normal')
link('TSPunctBracket', 'MyTag')
link('TSFunction', 'Function')
link('Folded', 'Comment')
link('TSKeyword', 'Keyword')
