-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color9 = '#1da90d'
local Color4 = '#d0a00f'
local Color11 = '#d4efef'
local Color1 = '#339991'
local Color7 = '#03810d'
local Color3 = '#037ed1'
local Color19 = '#00b2a6'
local Color14 = '#e1f4f4'
local Color6 = '#009c8f'
local Color5 = '#8c9898'
local Color13 = '#000000'
local Color8 = '#7537d7'
local Color2 = '#f7775a'
local Color0 = '#A4EF58'
local Color12 = '#3b4141'
local Color10 = '#c0571f'
local Color15 = '#c5e5d7'
local Color17 = '#b6e7e5'
local Color18 = '#7ec0bc'
local Color16 = '#e4e1dd'

highlight('Type', nil, Color0, nil)
highlight('Comment', nil, Color1, 'italic')
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('String', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Identifier', nil, Color9, nil)
highlight('Number', nil, Color10, nil)
highlight('StatusLine', Color12, Color11, nil)
highlight('WildMenu', Color14, Color13, nil)
highlight('Pmenu', Color14, Color13, nil)
highlight('PmenuSel', Color13, Color14, nil)
highlight('PmenuThumb', Color14, Color13, nil)
highlight('DiffAdd', Color15, nil, nil)
highlight('DiffDelete', Color16, nil, nil)
highlight('Normal', Color14, Color13, nil)
highlight('Visual', Color17, nil, nil)
highlight('CursorLine', Color17, nil, nil)
highlight('ColorColumn', Color17, nil, nil)
highlight('SignColumn', Color14, nil, nil)
highlight('LineNr', nil, Color18, nil)
highlight('TabLine', Color11, Color1, nil)
highlight('TabLineSel', Color19, Color14, nil)
highlight('TabLineFill', Color11, Color1, nil)
highlight('TSPunctDelimiter', nil, Color13, nil)

link('TSNamespace', 'TSType')
link('Conditional', 'Operator')
link('TSProperty', 'TSField')
link('CursorLineNr', 'Identifier')
link('TSFloat', 'Number')
link('TSKeyword', 'Keyword')
link('TSField', 'Constant')
link('TelescopeNormal', 'Normal')
link('TSPunctBracket', 'MyTag')
link('TSTagDelimiter', 'Type')
link('TSFunction', 'Function')
link('TSNumber', 'Number')
link('TSType', 'Type')
link('TSParameterReference', 'TSParameter')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSRepeat', 'Repeat')
link('Whitespace', 'Comment')
link('TSOperator', 'Operator')
link('TSConstant', 'Constant')
link('TSLabel', 'Type')
link('TSParameter', 'Constant')
link('Macro', 'Function')
link('Folded', 'Comment')
link('NonText', 'Comment')
link('TSString', 'String')
link('Operator', 'Keyword')
link('TSConditional', 'Conditional')
link('TSComment', 'Comment')
link('TSFuncMacro', 'Macro')
link('TSTag', 'MyTag')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Repeat', 'Conditional')
