-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color15 = '#d3d7dc'
local Color2 = '#ee5f50'
local Color7 = '#41ad4e'
local Color12 = '#6f767d'
local Color3 = '#0aa3d6'
local Color1 = '#808892'
local Color13 = '#f5f8fc'
local Color0 = '#589f11'
local Color9 = '#ed7b89'
local Color14 = '#dee2e6'
local Color16 = '#898989'
local Color17 = '#444c54'
local Color10 = '#e3946a'
local Color4 = '#e39c03'
local Color5 = '#272d34'
local Color8 = '#b377e3'
local Color11 = '#EAECEE'
local Color6 = '#00b696'

highlight('Type', nil, Color0, nil)
highlight('Comment', nil, Color1, 'italic')
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('String', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Identifier', nil, Color9, nil)
highlight('Number', nil, Color10, nil)
highlight('StatusLine', Color12, Color11, nil)
highlight('WildMenu', Color13, Color5, nil)
highlight('Pmenu', Color13, Color5, nil)
highlight('PmenuSel', Color5, Color14, nil)
highlight('PmenuThumb', Color13, Color5, nil)
highlight('DiffAdd', Color13, nil, nil)
highlight('DiffDelete', Color13, nil, nil)
highlight('Normal', Color13, Color5, nil)
highlight('Visual', Color15, nil, nil)
highlight('CursorLine', Color15, nil, nil)
highlight('ColorColumn', Color15, nil, nil)
highlight('SignColumn', Color13, nil, nil)
highlight('LineNr', nil, Color16, nil)
highlight('TabLine', Color11, Color16, nil)
highlight('TabLineSel', Color17, Color14, nil)
highlight('TabLineFill', Color11, Color16, nil)
highlight('TSPunctDelimiter', nil, Color5, nil)

link('TSNamespace', 'TSType')
link('TSConstant', 'Constant')
link('TSLabel', 'Type')
link('NonText', 'Comment')
link('TSString', 'String')
link('TSTag', 'MyTag')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSParameter', 'Constant')
link('TSComment', 'Comment')
link('TSConditional', 'Conditional')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSField', 'Constant')
link('TSTagDelimiter', 'Type')
link('TSFuncMacro', 'Macro')
link('TSProperty', 'TSField')
link('Operator', 'Keyword')
link('TSRepeat', 'Repeat')
link('TSKeyword', 'Keyword')
link('TelescopeNormal', 'Normal')
link('Repeat', 'Conditional')
link('Conditional', 'Operator')
link('Folded', 'Comment')
link('Macro', 'Function')
link('TSOperator', 'Operator')
link('TSType', 'Type')
link('Whitespace', 'Comment')
link('TSFloat', 'Number')
link('CursorLineNr', 'Identifier')
link('TSFunction', 'Function')
link('TSPunctBracket', 'MyTag')
link('TSParameterReference', 'TSParameter')
link('TSNumber', 'Number')
