-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color5 = '#cfccd8'
local Color17 = '#59526c'
local Color14 = '#362d33'
local Color3 = '#4fc1e8'
local Color10 = '#eea67f'
local Color16 = '#43383a'
local Color1 = '#7c768c'
local Color2 = '#fb7a6c'
local Color6 = '#17d7b4'
local Color0 = '#77b03e'
local Color4 = '#dbc2a3'
local Color7 = '#69d2ab'
local Color8 = '#ad92ff'
local Color13 = '#1C1827'
local Color11 = '#171420'
local Color15 = '#1c1827'
local Color18 = '#ecc48c'
local Color12 = '#8b8698'
local Color9 = '#e38d97'

highlight('Type', nil, Color0, nil)
highlight('Comment', nil, Color1, 'italic')
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('String', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Identifier', nil, Color9, nil)
highlight('Number', nil, Color10, nil)
highlight('StatusLine', Color12, Color11, nil)
highlight('WildMenu', Color13, Color5, nil)
highlight('Pmenu', Color13, Color5, nil)
highlight('PmenuSel', Color5, Color14, nil)
highlight('PmenuThumb', Color13, Color5, nil)
highlight('DiffAdd', Color15, nil, nil)
highlight('DiffDelete', Color15, nil, nil)
highlight('Normal', Color13, Color5, nil)
highlight('Visual', Color16, nil, nil)
highlight('CursorLine', Color16, nil, nil)
highlight('ColorColumn', Color16, nil, nil)
highlight('SignColumn', Color13, nil, nil)
highlight('LineNr', nil, Color17, nil)
highlight('TabLine', Color11, Color17, nil)
highlight('TabLineSel', Color18, Color14, nil)
highlight('TabLineFill', Color11, Color17, nil)
highlight('TSPunctDelimiter', nil, Color5, nil)

link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSTag', 'MyTag')
link('TelescopeNormal', 'Normal')
link('CursorLineNr', 'Identifier')
link('NonText', 'Comment')
link('TSParameterReference', 'TSParameter')
link('TSOperator', 'Operator')
link('TSProperty', 'TSField')
link('TSComment', 'Comment')
link('TSPunctBracket', 'MyTag')
link('TSField', 'Constant')
link('TSConditional', 'Conditional')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSLabel', 'Type')
link('TSParameter', 'Constant')
link('Folded', 'Comment')
link('Whitespace', 'Comment')
link('Macro', 'Function')
link('TSType', 'Type')
link('Operator', 'Keyword')
link('TSNumber', 'Number')
link('TSConstant', 'Constant')
link('TSKeyword', 'Keyword')
link('TSString', 'String')
link('TSFunction', 'Function')
link('TSNamespace', 'TSType')
link('TSFloat', 'Number')
link('TSTagDelimiter', 'Type')
link('Repeat', 'Conditional')
link('Conditional', 'Operator')
link('TSFuncMacro', 'Macro')
link('TSRepeat', 'Repeat')
