-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color14 = '#c9c4d6'
local Color17 = '#292248'
local Color5 = '#5a5565'
local Color9 = '#D65170'
local Color18 = '#38324b'
local Color0 = '#2C729E'
local Color2 = '#C13838'
local Color6 = '#89C4FF'
local Color13 = '#171322'
local Color4 = '#585785'
local Color10 = '#3D8DE2'
local Color11 = '#120f1b'
local Color16 = '#2f1825'
local Color8 = '#2BD3E2'
local Color7 = '#6DBBFF'
local Color12 = '#857e96'
local Color15 = '#16272b'
local Color1 = '#534a6b'
local Color3 = '#7A63ED'

highlight('Type', nil, Color0, nil)
highlight('Comment', nil, Color1, 'italic')
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('String', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Identifier', nil, Color9, nil)
highlight('Number', nil, Color10, nil)
highlight('StatusLine', Color12, Color11, nil)
highlight('WildMenu', Color13, Color14, nil)
highlight('Pmenu', Color13, Color14, nil)
highlight('PmenuSel', Color14, Color13, nil)
highlight('PmenuThumb', Color13, Color14, nil)
highlight('DiffAdd', Color15, nil, nil)
highlight('DiffDelete', Color16, nil, nil)
highlight('Normal', Color13, Color14, nil)
highlight('Visual', Color17, nil, nil)
highlight('CursorLine', Color17, nil, nil)
highlight('ColorColumn', Color17, nil, nil)
highlight('SignColumn', Color13, nil, nil)
highlight('LineNr', nil, Color18, nil)
highlight('TabLine', Color11, Color1, nil)
highlight('TabLineSel', Color3, Color13, nil)
highlight('TabLineFill', Color11, Color1, nil)
highlight('TSPunctDelimiter', nil, Color14, nil)

link('Conditional', 'Operator')
link('TSType', 'Type')
link('TSField', 'Constant')
link('TSParameter', 'Constant')
link('TSLabel', 'Type')
link('TSPunctBracket', 'MyTag')
link('TSNumber', 'Number')
link('TSKeyword', 'Keyword')
link('TSFuncMacro', 'Macro')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('NonText', 'Comment')
link('TSFunction', 'Function')
link('Operator', 'Keyword')
link('Macro', 'Function')
link('TSTag', 'MyTag')
link('CursorLineNr', 'Identifier')
link('Repeat', 'Conditional')
link('Folded', 'Comment')
link('TSNamespace', 'TSType')
link('TelescopeNormal', 'Normal')
link('TSTagDelimiter', 'Type')
link('TSConstant', 'Constant')
link('TSProperty', 'TSField')
link('TSRepeat', 'Repeat')
link('TSFloat', 'Number')
link('TSString', 'String')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSComment', 'Comment')
link('TSParameterReference', 'TSParameter')
link('Whitespace', 'Comment')
link('TSOperator', 'Operator')
link('TSConditional', 'Conditional')
