-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color3 = '#10bdc9'
local Color12 = '#0f1c21'
local Color0 = '#2C729E'
local Color1 = '#45565c'
local Color11 = '#78868a'
local Color6 = '#0187a6'
local Color9 = '#d6724d'
local Color17 = '#2d3c42'
local Color14 = '#0f2f2b'
local Color15 = '#282024'
local Color16 = '#0c303a'
local Color13 = '#c2ced1'
local Color5 = '#525f63'
local Color8 = '#9c8acf'
local Color4 = '#d6ac63'
local Color7 = '#6bc793'
local Color2 = '#C13838'
local Color10 = '#0e171c'

highlight('Type', nil, Color0, nil)
highlight('Comment', nil, Color1, 'italic')
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('String', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Identifier', nil, Color9, nil)
highlight('Number', nil, Color6, nil)
highlight('StatusLine', Color11, Color10, nil)
highlight('WildMenu', Color12, Color13, nil)
highlight('Pmenu', Color12, Color13, nil)
highlight('PmenuSel', Color13, Color12, nil)
highlight('PmenuThumb', Color12, Color13, nil)
highlight('DiffAdd', Color14, nil, nil)
highlight('DiffDelete', Color15, nil, nil)
highlight('Normal', Color12, Color13, nil)
highlight('Visual', Color16, nil, nil)
highlight('CursorLine', Color16, nil, nil)
highlight('ColorColumn', Color16, nil, nil)
highlight('SignColumn', Color12, nil, nil)
highlight('LineNr', nil, Color17, nil)
highlight('TabLine', Color10, Color1, nil)
highlight('TabLineSel', Color6, Color12, nil)
highlight('TabLineFill', Color10, Color1, nil)
highlight('TSPunctDelimiter', nil, Color13, nil)

link('TSParameter', 'Constant')
link('TSComment', 'Comment')
link('Whitespace', 'Comment')
link('TSTagDelimiter', 'Type')
link('TSTag', 'MyTag')
link('TSOperator', 'Operator')
link('TSConstant', 'Constant')
link('TSFloat', 'Number')
link('TSFuncMacro', 'Macro')
link('TSFunction', 'Function')
link('TSKeyword', 'Keyword')
link('Repeat', 'Conditional')
link('Operator', 'Keyword')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSRepeat', 'Repeat')
link('NonText', 'Comment')
link('Folded', 'Comment')
link('TSField', 'Constant')
link('CursorLineNr', 'Identifier')
link('TSConditional', 'Conditional')
link('TSType', 'Type')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TelescopeNormal', 'Normal')
link('TSNumber', 'Number')
link('TSString', 'String')
link('Conditional', 'Operator')
link('TSProperty', 'TSField')
link('TSNamespace', 'TSType')
link('TSPunctBracket', 'MyTag')
link('TSParameterReference', 'TSParameter')
link('TSLabel', 'Type')
link('Macro', 'Function')
