-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color1 = '#4d5971'
local Color0 = '#A4EF58'
local Color11 = '#161c28'
local Color18 = '#333c4e'
local Color3 = '#69C3FF'
local Color6 = '#22ECDB'
local Color9 = '#FF738A'
local Color13 = '#121721'
local Color10 = '#FF955C'
local Color15 = '#17312d'
local Color5 = '#565c66'
local Color14 = '#c9cfda'
local Color16 = '#301f23'
local Color7 = '#3CEC85'
local Color17 = '#262e3c'
local Color4 = '#EACD61'
local Color8 = '#B78AFF'
local Color2 = '#E35535'
local Color19 = '#8196b5'
local Color12 = '#81899a'

highlight('Type', nil, Color0, nil)
highlight('Comment', nil, Color1, 'italic')
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('String', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Identifier', nil, Color9, nil)
highlight('Number', nil, Color10, nil)
highlight('StatusLine', Color12, Color11, nil)
highlight('WildMenu', Color13, Color14, nil)
highlight('Pmenu', Color13, Color14, nil)
highlight('PmenuSel', Color14, Color13, nil)
highlight('PmenuThumb', Color13, Color14, nil)
highlight('DiffAdd', Color15, nil, nil)
highlight('DiffDelete', Color16, nil, nil)
highlight('Normal', Color13, Color14, nil)
highlight('Visual', Color17, nil, nil)
highlight('CursorLine', Color17, nil, nil)
highlight('ColorColumn', Color17, nil, nil)
highlight('SignColumn', Color13, nil, nil)
highlight('LineNr', nil, Color18, nil)
highlight('TabLine', Color11, Color1, nil)
highlight('TabLineSel', Color19, Color13, nil)
highlight('TabLineFill', Color11, Color1, nil)
highlight('TSPunctDelimiter', nil, Color14, nil)

link('Conditional', 'Operator')
link('CursorLineNr', 'Identifier')
link('TSNumber', 'Number')
link('TSConstant', 'Constant')
link('TSFunction', 'Function')
link('TSNamespace', 'TSType')
link('TSFloat', 'Number')
link('TSFuncMacro', 'Macro')
link('TSTagDelimiter', 'Type')
link('TSComment', 'Comment')
link('TSRepeat', 'Repeat')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSParameter', 'Constant')
link('TSType', 'Type')
link('Repeat', 'Conditional')
link('TSString', 'String')
link('TSProperty', 'TSField')
link('TSOperator', 'Operator')
link('TSTag', 'MyTag')
link('Operator', 'Keyword')
link('NonText', 'Comment')
link('TSConditional', 'Conditional')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Macro', 'Function')
link('TSParameterReference', 'TSParameter')
link('TelescopeNormal', 'Normal')
link('TSField', 'Constant')
link('Whitespace', 'Comment')
link('TSKeyword', 'Keyword')
link('Folded', 'Comment')
link('TSPunctBracket', 'MyTag')
link('TSLabel', 'Type')
