-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color14 = '#161d26'
local Color13 = '#c9d0d8'
local Color17 = '#153946'
local Color0 = '#3585bb'
local Color12 = '#838d99'
local Color8 = '#a85ff1'
local Color9 = '#c62f52'
local Color15 = '#132e31'
local Color16 = '#332528'
local Color18 = '#35404e'
local Color10 = '#d4770c'
local Color4 = '#c7910c'
local Color3 = '#11B7D4'
local Color5 = '#596069'
local Color1 = '#4e5c6d'
local Color2 = '#E35535'
local Color6 = '#38c7bd'
local Color7 = '#00a884'
local Color11 = '#12181f'

highlight('Type', nil, Color0, nil)
highlight('Comment', nil, Color1, 'italic')
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('String', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Identifier', nil, Color9, nil)
highlight('Number', nil, Color10, nil)
highlight('StatusLine', Color12, Color11, nil)
highlight('WildMenu', Color14, Color13, nil)
highlight('Pmenu', Color14, Color13, nil)
highlight('PmenuSel', Color13, Color14, nil)
highlight('PmenuThumb', Color14, Color13, nil)
highlight('DiffAdd', Color15, nil, nil)
highlight('DiffDelete', Color16, nil, nil)
highlight('Normal', Color14, Color13, nil)
highlight('Visual', Color17, nil, nil)
highlight('CursorLine', Color17, nil, nil)
highlight('ColorColumn', Color17, nil, nil)
highlight('SignColumn', Color14, nil, nil)
highlight('LineNr', nil, Color18, nil)
highlight('TabLine', Color11, Color1, nil)
highlight('TabLineSel', Color3, Color14, nil)
highlight('TabLineFill', Color11, Color1, nil)
highlight('TSPunctDelimiter', nil, Color13, nil)

link('TSConstant', 'Constant')
link('TSNumber', 'Number')
link('TSPunctBracket', 'MyTag')
link('TSTagDelimiter', 'Type')
link('Conditional', 'Operator')
link('TSFunction', 'Function')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Macro', 'Function')
link('TSNamespace', 'TSType')
link('TelescopeNormal', 'Normal')
link('TSString', 'String')
link('TSParameterReference', 'TSParameter')
link('Operator', 'Keyword')
link('Repeat', 'Conditional')
link('TSTag', 'MyTag')
link('TSKeyword', 'Keyword')
link('TSParameter', 'Constant')
link('TSConditional', 'Conditional')
link('TSFuncMacro', 'Macro')
link('TSProperty', 'TSField')
link('TSLabel', 'Type')
link('Folded', 'Comment')
link('TSOperator', 'Operator')
link('NonText', 'Comment')
link('Whitespace', 'Comment')
link('CursorLineNr', 'Identifier')
link('TSComment', 'Comment')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSRepeat', 'Repeat')
link('TSField', 'Constant')
link('TSFloat', 'Number')
link('TSType', 'Type')
