-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color13 = '#d3d8e1'
local Color15 = '#203d3d'
local Color7 = '#3CEC85'
local Color8 = '#B78AFF'
local Color18 = '#3b465b'
local Color12 = '#8c94a3'
local Color1 = '#54617b'
local Color0 = '#A4EF58'
local Color2 = '#E35535'
local Color11 = '#181f2c'
local Color9 = '#FF738A'
local Color16 = '#382b33'
local Color19 = '#8196b5'
local Color3 = '#69C3FF'
local Color4 = '#EACD61'
local Color14 = '#1c2433'
local Color6 = '#22ECDB'
local Color10 = '#FF955C'
local Color17 = '#2f394b'
local Color5 = '#606774'

highlight('Type', nil, Color0, nil)
highlight('Comment', nil, Color1, 'italic')
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('String', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Identifier', nil, Color9, nil)
highlight('Number', nil, Color10, nil)
highlight('StatusLine', Color12, Color11, nil)
highlight('WildMenu', Color14, Color13, nil)
highlight('Pmenu', Color14, Color13, nil)
highlight('PmenuSel', Color13, Color14, nil)
highlight('PmenuThumb', Color14, Color13, nil)
highlight('DiffAdd', Color15, nil, nil)
highlight('DiffDelete', Color16, nil, nil)
highlight('Normal', Color14, Color13, nil)
highlight('Visual', Color17, nil, nil)
highlight('CursorLine', Color17, nil, nil)
highlight('ColorColumn', Color17, nil, nil)
highlight('SignColumn', Color14, nil, nil)
highlight('LineNr', nil, Color18, nil)
highlight('TabLine', Color11, Color1, nil)
highlight('TabLineSel', Color19, Color14, nil)
highlight('TabLineFill', Color11, Color1, nil)
highlight('TSPunctDelimiter', nil, Color13, nil)

link('Folded', 'Comment')
link('TSFunction', 'Function')
link('TSConstant', 'Constant')
link('TSComment', 'Comment')
link('Whitespace', 'Comment')
link('TSString', 'String')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSKeyword', 'Keyword')
link('TSNamespace', 'TSType')
link('TSFuncMacro', 'Macro')
link('TSType', 'Type')
link('TSLabel', 'Type')
link('Macro', 'Function')
link('TSField', 'Constant')
link('Repeat', 'Conditional')
link('TSPunctBracket', 'MyTag')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSFloat', 'Number')
link('TSProperty', 'TSField')
link('Operator', 'Keyword')
link('TSOperator', 'Operator')
link('TSTag', 'MyTag')
link('TelescopeNormal', 'Normal')
link('CursorLineNr', 'Identifier')
link('TSNumber', 'Number')
link('TSConditional', 'Conditional')
link('TSParameterReference', 'TSParameter')
link('TSRepeat', 'Repeat')
link('TSParameter', 'Constant')
link('TSTagDelimiter', 'Type')
link('NonText', 'Comment')
link('Conditional', 'Operator')
