-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color2 = '#ff7e70'
local Color0 = '#A4EF58'
local Color11 = '#749ab9'
local Color6 = '#22D3B1'
local Color8 = '#b8b3ff'
local Color1 = '#6d8ca4'
local Color16 = '#2a6ea4'
local Color12 = '#0a2439'
local Color10 = '#ffaf94'
local Color7 = '#9dffbd'
local Color13 = '#0c2a42'
local Color15 = '#27525e'
local Color5 = '#c3dcf0'
local Color4 = '#fff0a6'
local Color14 = '#1e4454'
local Color9 = '#f994bf'
local Color3 = '#82c4ff'
local Color17 = '#9dffd9'

highlight('Type', nil, Color0, nil)
highlight('Comment', nil, Color1, 'italic')
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Conditional', nil, Color4, nil)
highlight('Repeat', nil, Color4, nil)
highlight('Operator', nil, Color5, nil)
highlight('Type', nil, Color6, nil)
highlight('String', nil, Color7, nil)
highlight('Type', nil, Color8, nil)
highlight('Identifier', nil, Color9, nil)
highlight('Number', nil, Color10, nil)
highlight('StatusLine', Color11, Color12, nil)
highlight('WildMenu', Color13, Color5, nil)
highlight('Pmenu', Color13, Color5, nil)
highlight('PmenuSel', Color5, Color14, nil)
highlight('PmenuThumb', Color13, Color5, nil)
highlight('DiffAdd', Color13, nil, nil)
highlight('DiffDelete', Color13, nil, nil)
highlight('Normal', Color13, Color5, nil)
highlight('Visual', Color15, nil, nil)
highlight('CursorLine', Color15, nil, nil)
highlight('ColorColumn', Color15, nil, nil)
highlight('SignColumn', Color13, nil, nil)
highlight('LineNr', nil, Color16, nil)
highlight('TabLine', Color12, Color16, nil)
highlight('TabLineSel', Color17, Color14, nil)
highlight('TabLineFill', Color12, Color16, nil)
highlight('TSPunctDelimiter', nil, Color5, nil)

link('TSString', 'String')
link('NonText', 'Comment')
link('TSRepeat', 'Repeat')
link('TSFunction', 'Function')
link('Whitespace', 'Comment')
link('Repeat', 'Conditional')
link('TSConstant', 'Constant')
link('TSTag', 'MyTag')
link('TSParameterReference', 'TSParameter')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSParameter', 'Constant')
link('TelescopeNormal', 'Normal')
link('CursorLineNr', 'Identifier')
link('TSTagDelimiter', 'Type')
link('Conditional', 'Operator')
link('TSLabel', 'Type')
link('Operator', 'Keyword')
link('TSFuncMacro', 'Macro')
link('TSFloat', 'Number')
link('TSConditional', 'Conditional')
link('TSField', 'Constant')
link('Folded', 'Comment')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('TSOperator', 'Operator')
link('Macro', 'Function')
link('TSNamespace', 'TSType')
link('TSType', 'Type')
link('TSProperty', 'TSField')
link('TSComment', 'Comment')
link('TSKeyword', 'Keyword')
link('TSPunctBracket', 'MyTag')
link('TSNumber', 'Number')
